name: Pull Request Validation

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Lint HTML Files
        run: npx htmlhint src/**/*.html

      - name: Lint CSS Files
        run: npx stylelint styles/**/*.css

  build:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build Website
        run: npx parcel build src/index.html
